services:

  postgres-test:
    image: postgres:15-alpine
    container_name: postgres-test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - test

  redis-test:
    image: redis:alpine
    container_name: redis-test
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - test

networks:
  test:
